def print_in_block(message):
    """
    print_in_block prints a message fancy
    """
    print("="*4, message)


print_in_block("knock knock!")
print_in_block("\twho's there?")
print_in_block("hatch")
print_in_block("\thatch who?")
print_in_block("bless you!")
print('\n')
print_in_block("knock knock!")
print_in_block("\twho's there?")
print_in_block("ether")
print_in_block("\tether who?")
print_in_block("ether bunny here!")
print('\n')
print_in_block("knock knock!")
print_in_block("\twho's there?")
print_in_block("Stella")
print_in_block("\tStella who?")
print_in_block("Stellanother ether bunny here!")
print('\n')
print_in_block("knock knock!")
print_in_block("\twho's there?")
print_in_block("cargo")
print_in_block("\tcargo who?")
print_in_block("Cargo beep beep and run over all the ether bunnies!")
print('\n')
print_in_block("knock knock!")
print_in_block("\twho's there?")
print_in_block("owls go")
print_in_block("\towls go who?")
print_in_block("exactly!")
